export const MOCK_EPISODES = [
    {
      id: "1",
      series: "Series A",
      title: "Episode 1",
      description: "Description for episode 1",
      seasonNumber: 1,
      episodeNumber: 1,
      releaseDate: "2021-01-01",
      imdbId: "tt1234567",
    },
    {
      id: "2",
      series: "Series A",
      title: "Episode 2",
      description: "Description for episode 2",
      seasonNumber: 1,
      episodeNumber: 2,
      releaseDate: "2021-01-08",
      imdbId: "tt1234568",
    },
    {
      id: "3",
      series: "Series B",
      title: "Episode 1",
      description: "Description for episode 1 of Series B",
      seasonNumber: 1,
      episodeNumber: 1,
      releaseDate: "2021-02-01",
      imdbId: "tt1234569",
    },
    {
      id: "4",
      series: "Series A",
      title: "Episode 3",
      description: "Description for episode 3",
      seasonNumber: 1,
      episodeNumber: 3,
      releaseDate: "2021-01-15",
      imdbId: "tt1234570",
    },
    {
      id: "5",
      series: "Series A",
      title: "Episode 4",
      description: "Description for episode 4",
      seasonNumber: 1,
      episodeNumber: 4,
      releaseDate: "2021-01-22",
      imdbId: "tt1234571",
    },
    {
      id: "6",
      series: "Series A",
      title: "Episode 5",
      description: "Description for episode 5",
      seasonNumber: 1,
      episodeNumber: 5,
      releaseDate: "2021-01-29",
      imdbId: "tt1234572",
    },
    {
      id: "7",
      series: "Series B",
      title: "Episode 2",
      description: "Description for episode 2 of Series B",
      seasonNumber: 1,
      episodeNumber: 2,
      releaseDate: "2021-02-08",
      imdbId: "tt1234573",
    },
    {
      id: "8",
      series: "Series B",
      title: "Episode 3",
      description: "Description for episode 3 of Series B",
      seasonNumber: 1,
      episodeNumber: 3,
      releaseDate: "2021-02-15",
      imdbId: "tt1234574",
    },
    {
      id: "9",
      series: "Series B",
      title: "Episode 4",
      description: "Description for episode 4 of Series B",
      seasonNumber: 1,
      episodeNumber: 4,
      releaseDate: "2021-02-22",
      imdbId: "tt1234575",
    },
    {
      id: "10",
      series: "Series C",
      title: "Episode 1",
      description: "Description for episode 1 of Series C",
      seasonNumber: 1,
      episodeNumber: 1,
      releaseDate: "2021-03-01",
      imdbId: "tt1234576",
    },
    {
      id: "11",
      series: "Series C",
      title: "Episode 2",
      description: "Description for episode 2 of Series C",
      seasonNumber: 1,
      episodeNumber: 2,
      releaseDate: "2021-03-08",
      imdbId: "tt1234577",
    },
    {
      id: "12",
      series: "Series C",
      title: "Episode 3",
      description: "Description for episode 3 of Series C",
      seasonNumber: 1,
      episodeNumber: 3,
      releaseDate: "2021-03-15",
      imdbId: "tt1234578",
    },
    {
      id: "13",
      series: "Series D",
      title: "Episode 1",
      description: "Description for episode 1 of Series D",
      seasonNumber: 1,
      episodeNumber: 1,
      releaseDate: "2021-04-01",
      imdbId: "tt1234579",
    },
    {
      id: "14",
      series: "Series D",
      title: "Episode 2",
      description: "Description for episode 2 of Series D",
      seasonNumber: 1,
      episodeNumber: 2,
      releaseDate: "2021-04-08",
      imdbId: "tt1234580",
    },
    {
      id: "15",
      series: "Series D",
      title: "Episode 3",
      description: "Description for episode 3 of Series D",
      seasonNumber: 1,
      episodeNumber: 3,
      releaseDate: "2021-04-15",
      imdbId: "tt1234581",
    },
    {
      id: "16",
      series: "Series E",
      title: "Episode 1",
      description: "Description for episode 1 of Series E",
      seasonNumber: 1,
      episodeNumber: 1,
      releaseDate: "2021-05-01",
      imdbId: "tt1234582",
    },
    {
      id: "17",
      series: "Series E",
      title: "Episode 2",
      description: "Description for episode 2 of Series E",
      seasonNumber: 1,
      episodeNumber: 2,
      releaseDate: "2021-05-08",
      imdbId: "tt1234583",
    },
    {
      id: "18",
      series: "Series E",
      title: "Episode 3",
      description: "Description for episode 3 of Series E",
      seasonNumber: 1,
      episodeNumber: 3,
      releaseDate: "2021-05-15",
      imdbId: "tt1234584",
    },
    {
      id: "19",
      series: "Series F",
      title: "Episode 1",
      description: "Description for episode 1 of Series F",
      seasonNumber: 1,
      episodeNumber: 1,
      releaseDate: "2021-06-01",
      imdbId: "tt1234585",
    },
    {
      id: "20",
      series: "Series F",
      title: "Episode 2",
      description: "Description for episode 2 of Series F",
      seasonNumber: 1,
      episodeNumber: 2,
      releaseDate: "2021-06-08",
      imdbId: "tt1234586",
    },
  ];